### ISSUE TITLE
Can not create build for arm/arm64

### ISSUE THREAD

**Issue by sw-tt-shirinafrozansari** [react-native-webview/react-native-webview#2034]
**Bug description:**

I integrated react-native-webview for windows. Try to run from vs code and it worked completely fine.
But when I try to create arm build from VS 2019, It gives me below error:
[msg]cannot open input file [context]Error opening or processing WinMD ARM\release
 \webviewbridgecomponent\webviewbridgecomponent.winmd. HRESULT 0x80070003.

**To Reproduce:**

=>integrate react-native-webview for windows in vscode project 
=>Open any url in webview
=>Run in VScode
=>Open VS 19 and try to create arm/arm64 package build

**Expected behavior:**

As My application is targeting Hololens, I have to create ARM release package file to test in Hololens 2. Is react-native-webview supports arm/arm64 build? Or Am I missing anything in the development? 
Any help would be appreciated!

**Screenshots/Videos:**
![WebViewARMError](https://user-images.githubusercontent.com/30889172/121027108-5516b100-c7c4-11eb-8ad9-9c231a597c28.PNG)

**Environment:**
 - OS: Windows 
 - OS version: Windows 10
 - react-native version: 0.64.1
 - react-native-webview version: 11.6.1

**Comment by sw-tt-shirinafrozansari** [comment]
@asklar 
- Are you seeing the problem only on Release? does ARM64 Debug build ok?
**Same issue in both release and debug**
- Do you need ARM64 only or also ARM(32)?
   **Both ARM & ARM64**
- It will help if you can copy/paste the content of the Output window after trying to build, that will contain more context as to where the errors are originating 
      **Output file content below:**
      Build started...
1>------ Build started: Project: ReactNativeWebView, Configuration: Debug ARM ------
1>MIDLRT Processing D:\AtheerAir\Workspace\sw-tt-atheerair-react-native\WebViewDemo\node_modules\react-native-webview\windows\ReactNativeWebView\ReactWebView.idl
1>ReactWebView.idl
1>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt\winrtbase.idl
1>winrtbase.idl
1>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt\midlbase.idl
1>midlbase.idl
1>Processing WinMD d:\atheerair\workspace\sw-tt-atheerair-react-native\webviewdemo\node_modules\react-native-windows\target\arm\debug\microsoft.reactnative\microsoft.reactnative.winmd
1>Processing WinMD d:\atheerair\workspace\sw-tt-atheerair-react-native\webviewdemo\windows\arm\debug\webviewbridgecomponent\webviewbridgecomponent.winmd
1>midlrt : error MIDL1001: [msg]cannot open input file [context]Error opening or processing WinMD d:\atheerair\workspace\sw-tt-atheerair-react-native\webviewdemo\windows\arm\debug\webviewbridgecomponent\webviewbridgecomponent.winmd. HRESULT 0x80070003.
1>D:\AtheerAir\Workspace\sw-tt-atheerair-react-native\WebViewDemo\node_modules\react-native-webview\windows\ReactNativeWebView\ReactWebView.idl(1): error MIDL5157: [msg]An invalid winmd file was specified for import [context]: D:\AtheerAir\Workspace\sw-tt-atheerair-react-native\WebViewDemo\windows\ARM\Debug\WebViewBridgeComponent\WebViewBridgeComponent.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ai.machinelearning.machinelearningcontract\2.0.0.0\windows.ai.machinelearning.machinelearningcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ai.machinelearning.preview.machinelearningpreviewcontract\2.0.0.0\windows.ai.machinelearning.preview.machinelearningpreviewcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.background.callsbackgroundcontract\2.0.0.0\windows.applicationmodel.calls.background.callsbackgroundcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.callsphonecontract\5.0.0.0\windows.applicationmodel.calls.callsphonecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.callsvoipcontract\4.0.0.0\windows.applicationmodel.calls.callsvoipcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.communicationblocking.communicationblockingcontract\2.0.0.0\windows.applicationmodel.communicationblocking.communicationblockingcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.socialinfo.socialinfocontract\2.0.0.0\windows.applicationmodel.socialinfo.socialinfocontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.startuptaskcontract\3.0.0.0\windows.applicationmodel.startuptaskcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.custom.customdevicecontract\1.0.0.0\windows.devices.custom.customdevicecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.deviceslowlevelcontract\3.0.0.0\windows.devices.deviceslowlevelcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.printers.printerscontract\1.0.0.0\windows.devices.printers.printerscontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.smartcards.smartcardbackgroundtriggercontract\3.0.0.0\windows.devices.smartcards.smartcardbackgroundtriggercontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.smartcards.smartcardemulatorcontract\6.0.0.0\windows.devices.smartcards.smartcardemulatorcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.foundation.foundationcontract\3.0.0.0\windows.foundation.foundationcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.foundation.universalapicontract\8.0.0.0\windows.foundation.universalapicontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.gaming.xboxlive.storageapicontract\1.0.0.0\windows.gaming.xboxlive.storageapicontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.graphics.printing3d.printing3dcontract\4.0.0.0\windows.graphics.printing3d.printing3dcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.networking.connectivity.wwancontract\2.0.0.0\windows.networking.connectivity.wwancontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.networking.sockets.controlchanneltriggercontract\3.0.0.0\windows.networking.sockets.controlchanneltriggercontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.maps.guidancecontract\3.0.0.0\windows.services.maps.guidancecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.maps.localsearchcontract\4.0.0.0\windows.services.maps.localsearchcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.store.storecontract\4.0.0.0\windows.services.store.storecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.targetedcontent.targetedcontentcontract\1.0.0.0\windows.services.targetedcontent.targetedcontentcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.profilehardwaretokencontract\1.0.0.0\windows.system.profile.profilehardwaretokencontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.profilesharedmodecontract\2.0.0.0\windows.system.profile.profilesharedmodecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.systemmanufacturers.systemmanufacturerscontract\3.0.0.0\windows.system.profile.systemmanufacturers.systemmanufacturerscontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.systemmanagementcontract\6.0.0.0\windows.system.systemmanagementcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ui.viewmanagement.viewmanagementviewscalingcontract\1.0.0.0\windows.ui.viewmanagement.viewmanagementviewscalingcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ui.xaml.core.direct.xamldirectcontract\2.0.0.0\windows.ui.xaml.core.direct.xamldirectcontract.winmd
1>D:\AtheerAir\Workspace\sw-tt-atheerair-react-native\WebViewDemo\node_modules\react-native-webview\windows\ReactNativeWebView\ReactWebView.idl(8): warning MIDL2214: [msg]semantic check incomplete due to previous errors
1>Done building project "ReactNativeWebView.vcxproj" -- FAILED.
2>------ Build started: Project: WebViewDemo, Configuration: Debug ARM ------
2>This program is blocked by group policy. For more information, contact your system administrator.
2>- Checking auto-linked files...
2>ΓêÜ Checking auto-linked files...
2>Success: No auto-linking changes necessary. (3037ms)
2>MIDLRT Processing D:\AtheerAir\Workspace\sw-tt-atheerair-react-native\WebViewDemo\windows\WebViewDemo\App.idl
2>App.idl
2>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt\winrtbase.idl
2>winrtbase.idl
2>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt\midlbase.idl
2>midlbase.idl
2>Processing WinMD d:\atheerair\workspace\sw-tt-atheerair-react-native\webviewdemo\windows\packages\microsoft.ui.xaml.2.3.191129002\lib\uap10.0\microsoft.ui.xaml.winmd
2>Processing WinMD d:\atheerair\workspace\sw-tt-atheerair-react-native\webviewdemo\node_modules\react-native-windows\target\arm\debug\microsoft.reactnative\microsoft.reactnative.winmd
2>Processing WinMD d:\atheerair\workspace\sw-tt-atheerair-react-native\webviewdemo\windows\arm\debug\reactnativewebview\reactnativewebview.winmd
2>midlrt : error MIDL1001: [msg]cannot open input file [context]Error opening or processing WinMD d:\atheerair\workspace\sw-tt-atheerair-react-native\webviewdemo\windows\arm\debug\reactnativewebview\reactnativewebview.winmd. HRESULT 0x80070002.
2>D:\AtheerAir\Workspace\sw-tt-atheerair-react-native\WebViewDemo\windows\WebViewDemo\App.idl(1): error MIDL5157: [msg]An invalid winmd file was specified for import [context]: D:\AtheerAir\Workspace\sw-tt-atheerair-react-native\WebViewDemo\windows\ARM\Debug\ReactNativeWebView\ReactNativeWebView.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ai.machinelearning.machinelearningcontract\2.0.0.0\windows.ai.machinelearning.machinelearningcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ai.machinelearning.preview.machinelearningpreviewcontract\2.0.0.0\windows.ai.machinelearning.preview.machinelearningpreviewcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.background.callsbackgroundcontract\2.0.0.0\windows.applicationmodel.calls.background.callsbackgroundcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.callsphonecontract\5.0.0.0\windows.applicationmodel.calls.callsphonecontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.callsvoipcontract\4.0.0.0\windows.applicationmodel.calls.callsvoipcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.communicationblocking.communicationblockingcontract\2.0.0.0\windows.applicationmodel.communicationblocking.communicationblockingcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.socialinfo.socialinfocontract\2.0.0.0\windows.applicationmodel.socialinfo.socialinfocontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.startuptaskcontract\3.0.0.0\windows.applicationmodel.startuptaskcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.custom.customdevicecontract\1.0.0.0\windows.devices.custom.customdevicecontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.deviceslowlevelcontract\3.0.0.0\windows.devices.deviceslowlevelcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.printers.printerscontract\1.0.0.0\windows.devices.printers.printerscontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.smartcards.smartcardbackgroundtriggercontract\3.0.0.0\windows.devices.smartcards.smartcardbackgroundtriggercontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.smartcards.smartcardemulatorcontract\6.0.0.0\windows.devices.smartcards.smartcardemulatorcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.foundation.foundationcontract\3.0.0.0\windows.foundation.foundationcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.foundation.universalapicontract\8.0.0.0\windows.foundation.universalapicontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.gaming.xboxlive.storageapicontract\1.0.0.0\windows.gaming.xboxlive.storageapicontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.graphics.printing3d.printing3dcontract\4.0.0.0\windows.graphics.printing3d.printing3dcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.networking.connectivity.wwancontract\2.0.0.0\windows.networking.connectivity.wwancontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.networking.sockets.controlchanneltriggercontract\3.0.0.0\windows.networking.sockets.controlchanneltriggercontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.maps.guidancecontract\3.0.0.0\windows.services.maps.guidancecontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.maps.localsearchcontract\4.0.0.0\windows.services.maps.localsearchcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.store.storecontract\4.0.0.0\windows.services.store.storecontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.targetedcontent.targetedcontentcontract\1.0.0.0\windows.services.targetedcontent.targetedcontentcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.profilehardwaretokencontract\1.0.0.0\windows.system.profile.profilehardwaretokencontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.profilesharedmodecontract\2.0.0.0\windows.system.profile.profilesharedmodecontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.systemmanufacturers.systemmanufacturerscontract\3.0.0.0\windows.system.profile.systemmanufacturers.systemmanufacturerscontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.systemmanagementcontract\6.0.0.0\windows.system.systemmanagementcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ui.viewmanagement.viewmanagementviewscalingcontract\1.0.0.0\windows.ui.viewmanagement.viewmanagementviewscalingcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ui.xaml.core.direct.xamldirectcontract\2.0.0.0\windows.ui.xaml.core.direct.xamldirectcontract.winmd
2>D:\AtheerAir\Workspace\sw-tt-atheerair-react-native\WebViewDemo\windows\WebViewDemo\App.idl(4): warning MIDL2214: [msg]semantic check incomplete due to previous errors
2>Done building project "WebViewDemo.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 5 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by asklar** [comment]
Some group policy in your system is blocking some of the tools:
```
2>------ Build started: Project: WebViewDemo, Configuration: Debug ARM ------
2>This program is blocked by group policy. For more information, contact your system administrator.
```

**Comment by sw-tt-shirinafrozansari** [comment]
@asklar 
Yes, Our infrastructure team is checking that. 
All projects in my system works fine and I can create arm/arm64 build as well.
Hence, I do not feel that this is the problem of this issue I am facing.

**Comment by asklar** [comment]
I validated that I can build the example app in this repo for ARM Debug (example\windows\WebViewWindows.sln). Try building that and see if you hit the same issue, my guess is something is wrong either in your app's config, or in your system all up (blocking some part of the build chain, like e.g. cppwinrt).

**Comment by sparmar-atheer** [comment]
@asklar Thanks for your help and looking into this. Really appreciate it. I set-up the same project on my Window Surface laptop and was able to build DEBUG ARM version. For Debug ARM64 I ran into the same issue. Were you able to build ARM64?

**Comment by asklar** [comment]
This PR should fix it @sparmar-atheer  :  #2044

**Comment by sparmar-atheer** [comment]
Wow. That was super fast. Thanks @asklar.

**Comment by sparmar-atheer** [comment]
@asklar @sw-tt-shirinafrozansari I tested after applying PR on my local machine and it did fix the issue.

**Comment by sw-tt-shirinafrozansari** [comment]
@asklar Thank you for your amazing support. Your PR #2044 worked for me as well.

**Comment by mdehghani65** [comment]
unfortunately I still have this issue using react-native-windows v64.0 and react-native-webview v11.13 when tryng to export an app package.
![Untitled](https://user-images.githubusercontent.com/28774905/129614724-70792a00-e247-42a3-a867-ac1d4a1f0ecd.png)
this is my build log:
`Build started...
1>------ Build started: Project: ReactNativeWebView, Configuration: Release Win32 ------
1>MIDLRT Processing C:\dadhesab\node_modules\react-native-webview\windows\ReactNativeWebView\ReactWebView.idl
1>ReactWebView.idl
1>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt\winrtbase.idl
1>winrtbase.idl
1>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt\midlbase.idl
1>midlbase.idl
1>Processing WinMD c:\dadhesab\node_modules\react-native-windows\target\x86\release\microsoft.reactnative\microsoft.reactnative.winmd
1>Processing WinMD c:\dadhesab\windows\release\webviewbridgecomponent\webviewbridgecomponent.winmd
1>midlrt : error MIDL1001: [msg]cannot open input file [context]Error opening or processing WinMD c:\dadhesab\windows\release\webviewbridgecomponent\webviewbridgecomponent.winmd. HRESULT 0x80070003.
1>C:\dadhesab\node_modules\react-native-webview\windows\ReactNativeWebView\ReactWebView.idl(1): error MIDL5157: [msg]An invalid winmd file was specified for import [context]: C:\dadhesab\windows\Release\WebViewBridgeComponent\WebViewBridgeComponent.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ai.machinelearning.machinelearningcontract\2.0.0.0\windows.ai.machinelearning.machinelearningcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ai.machinelearning.preview.machinelearningpreviewcontract\2.0.0.0\windows.ai.machinelearning.preview.machinelearningpreviewcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.background.callsbackgroundcontract\2.0.0.0\windows.applicationmodel.calls.background.callsbackgroundcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.callsphonecontract\5.0.0.0\windows.applicationmodel.calls.callsphonecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.callsvoipcontract\4.0.0.0\windows.applicationmodel.calls.callsvoipcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.communicationblocking.communicationblockingcontract\2.0.0.0\windows.applicationmodel.communicationblocking.communicationblockingcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.socialinfo.socialinfocontract\2.0.0.0\windows.applicationmodel.socialinfo.socialinfocontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.startuptaskcontract\3.0.0.0\windows.applicationmodel.startuptaskcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.custom.customdevicecontract\1.0.0.0\windows.devices.custom.customdevicecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.deviceslowlevelcontract\3.0.0.0\windows.devices.deviceslowlevelcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.printers.printerscontract\1.0.0.0\windows.devices.printers.printerscontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.smartcards.smartcardbackgroundtriggercontract\3.0.0.0\windows.devices.smartcards.smartcardbackgroundtriggercontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.smartcards.smartcardemulatorcontract\6.0.0.0\windows.devices.smartcards.smartcardemulatorcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.foundation.foundationcontract\3.0.0.0\windows.foundation.foundationcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.foundation.universalapicontract\8.0.0.0\windows.foundation.universalapicontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.gaming.xboxlive.storageapicontract\1.0.0.0\windows.gaming.xboxlive.storageapicontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.graphics.printing3d.printing3dcontract\4.0.0.0\windows.graphics.printing3d.printing3dcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.networking.connectivity.wwancontract\2.0.0.0\windows.networking.connectivity.wwancontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.networking.sockets.controlchanneltriggercontract\3.0.0.0\windows.networking.sockets.controlchanneltriggercontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.maps.guidancecontract\3.0.0.0\windows.services.maps.guidancecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.maps.localsearchcontract\4.0.0.0\windows.services.maps.localsearchcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.store.storecontract\4.0.0.0\windows.services.store.storecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.targetedcontent.targetedcontentcontract\1.0.0.0\windows.services.targetedcontent.targetedcontentcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.profilehardwaretokencontract\1.0.0.0\windows.system.profile.profilehardwaretokencontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.profilesharedmodecontract\2.0.0.0\windows.system.profile.profilesharedmodecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.systemmanufacturers.systemmanufacturerscontract\3.0.0.0\windows.system.profile.systemmanufacturers.systemmanufacturerscontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.systemmanagementcontract\6.0.0.0\windows.system.systemmanagementcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ui.viewmanagement.viewmanagementviewscalingcontract\1.0.0.0\windows.ui.viewmanagement.viewmanagementviewscalingcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ui.xaml.core.direct.xamldirectcontract\2.0.0.0\windows.ui.xaml.core.direct.xamldirectcontract.winmd
1>C:\dadhesab\node_modules\react-native-webview\windows\ReactNativeWebView\ReactWebView.idl(8): warning MIDL2214: [msg]semantic check incomplete due to previous errors
1>Done building project "ReactNativeWebView.vcxproj" -- FAILED.
2>------ Build started: Project: dadhesab, Configuration: Release Win32 ------
2>Running [npx --no-install react-native bundle --platform windows --entry-file index.js --bundle-output C:\dadhesab\windows\dadhesab\Bundle\index.windows.bundle --assets-dest C:\dadhesab\windows\dadhesab\Bundle --dev false --reset-cache --sourcemap-output C:\dadhesab\windows\Release\dadhesab\sourcemaps\react\index.windows.bundle.map ] to build bundle file.
2>EXEC : warning : the transform cache was reset.
2>                    Welcome to Metro!
2>              Fast - Scalable - Integrated
2>
2>
2>info Writing bundle output to:, C:\dadhesab\windows\dadhesab\Bundle\index.windows.bundle
2>info Writing sourcemap output to:, C:\dadhesab\windows\Release\dadhesab\sourcemaps\react\index.windows.bundle.map
2>info Done writing bundle output
2>info Done writing sourcemap output
2>info Copying 20 asset files
2>info Done copying assets
2>- Checking auto-linked files...
2>ΓêÜ Checking auto-linked files...
2>Success: No auto-linking changes necessary. (5305ms)
2>MIDLRT Processing C:\dadhesab\windows\dadhesab\App.idl
2>App.idl
2>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt\winrtbase.idl
2>winrtbase.idl
2>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt\midlbase.idl
2>midlbase.idl
2>Processing WinMD c:\dadhesab\windows\packages\microsoft.ui.xaml.2.3.191129002\lib\uap10.0\microsoft.ui.xaml.winmd
2>Processing WinMD c:\dadhesab\windows\release\reactnativewebview\reactnativewebview.winmd
2>midlrt : error MIDL1001: [msg]cannot open input file [context]Error opening or processing WinMD c:\dadhesab\windows\release\reactnativewebview\reactnativewebview.winmd. HRESULT 0x80070002.
2>C:\dadhesab\windows\dadhesab\App.idl(1): error MIDL5157: [msg]An invalid winmd file was specified for import [context]: C:\dadhesab\windows\Release\ReactNativeWebView\ReactNativeWebView.winmd
2>Processing WinMD c:\dadhesab\node_modules\react-native-windows\target\x86\release\microsoft.reactnative\microsoft.reactnative.winmd
2>Processing WinMD c:\dadhesab\windows\release\reactnativeasyncstorage\reactnativeasyncstorage.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ai.machinelearning.machinelearningcontract\2.0.0.0\windows.ai.machinelearning.machinelearningcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ai.machinelearning.preview.machinelearningpreviewcontract\2.0.0.0\windows.ai.machinelearning.preview.machinelearningpreviewcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.background.callsbackgroundcontract\2.0.0.0\windows.applicationmodel.calls.background.callsbackgroundcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.callsphonecontract\5.0.0.0\windows.applicationmodel.calls.callsphonecontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.calls.callsvoipcontract\4.0.0.0\windows.applicationmodel.calls.callsvoipcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.communicationblocking.communicationblockingcontract\2.0.0.0\windows.applicationmodel.communicationblocking.communicationblockingcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.socialinfo.socialinfocontract\2.0.0.0\windows.applicationmodel.socialinfo.socialinfocontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.applicationmodel.startuptaskcontract\3.0.0.0\windows.applicationmodel.startuptaskcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.custom.customdevicecontract\1.0.0.0\windows.devices.custom.customdevicecontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.deviceslowlevelcontract\3.0.0.0\windows.devices.deviceslowlevelcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.printers.printerscontract\1.0.0.0\windows.devices.printers.printerscontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.smartcards.smartcardbackgroundtriggercontract\3.0.0.0\windows.devices.smartcards.smartcardbackgroundtriggercontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.devices.smartcards.smartcardemulatorcontract\6.0.0.0\windows.devices.smartcards.smartcardemulatorcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.foundation.foundationcontract\3.0.0.0\windows.foundation.foundationcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.foundation.universalapicontract\8.0.0.0\windows.foundation.universalapicontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.gaming.xboxlive.storageapicontract\1.0.0.0\windows.gaming.xboxlive.storageapicontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.graphics.printing3d.printing3dcontract\4.0.0.0\windows.graphics.printing3d.printing3dcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.networking.connectivity.wwancontract\2.0.0.0\windows.networking.connectivity.wwancontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.networking.sockets.controlchanneltriggercontract\3.0.0.0\windows.networking.sockets.controlchanneltriggercontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.maps.guidancecontract\3.0.0.0\windows.services.maps.guidancecontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.maps.localsearchcontract\4.0.0.0\windows.services.maps.localsearchcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.store.storecontract\4.0.0.0\windows.services.store.storecontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.services.targetedcontent.targetedcontentcontract\1.0.0.0\windows.services.targetedcontent.targetedcontentcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.profilehardwaretokencontract\1.0.0.0\windows.system.profile.profilehardwaretokencontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.profilesharedmodecontract\2.0.0.0\windows.system.profile.profilesharedmodecontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.profile.systemmanufacturers.systemmanufacturerscontract\3.0.0.0\windows.system.profile.systemmanufacturers.systemmanufacturerscontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.system.systemmanagementcontract\6.0.0.0\windows.system.systemmanagementcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ui.viewmanagement.viewmanagementviewscalingcontract\1.0.0.0\windows.ui.viewmanagement.viewmanagementviewscalingcontract.winmd
2>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ui.xaml.core.direct.xamldirectcontract\2.0.0.0\windows.ui.xaml.core.direct.xamldirectcontract.winmd
2>C:\dadhesab\windows\dadhesab\App.idl(4): warning MIDL2214: [msg]semantic check incomplete due to previous errors
2>Done building project "dadhesab.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 6 up-to-date, 0 skipped ==========
========== Package: 0 succeeded, 4 failed ===========
========== App Bundle: 0 succeeded, 1 failed ===========`

there is not any error while building for debug. only errors when building for release

**Comment by mdehghani65** [comment]
@asklar can you please take a look?

**Comment by asklar** [comment]
@mdehghani65 can you please file a fresh issue and provide a repro project? Also please make sure you've updated to the latest 0.64 patch version
