### ISSUE TITLE
forceDarkOn stoped working after upgrade from 11.23.1 to 11.26.0 on android

### ISSUE THREAD

**Issue by ugened47** [react-native-webview/react-native-webview#2866]
**Bug description:**

Adding `forceDarkOn` takes no effect after upgrading `react-native-webview` 11.23.1 to 11.26.0
and `react-native` from 0.70.5 to 0.71.3

If I inspect the webview, and try to retrive the value of either `window.matchMedia('(prefers-color-scheme: light)').matches;` or `window.matchMedia('(prefers-color-scheme: dark)').matches;` I see that the value is `undefined` for some reason.

**Expected behavior:**

`forceDarkOn` should toggle dark mode

**Screenshots/Videos:**

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/9214135/220197566-2363b90d-7770-41a9-a5ad-1aabfb2d0f2e.png">

**Environment:**
 - OS: MacOS
 - OS version: 13.2.1
 - react-native version: 0.71.3
 - react-native-webview version: 11.26.0

**Comment by ugened47** [comment]
I tried to dig a bit more and found out that downgrading `react-native-webview` doesn't help, had to downgrade `react-native` package back to 0.70.5, where RN doesn't break things. However, wondering what can break things.

**Comment by andrewbush-papa** [comment]
When upgrading to RN 0.71.3 you would have set your Android `targetSdkVersion` to 33.  This API version no longer supports the `setForceDark()` method.

[Android Behavior Changes](https://developer.android.com/about/versions/13/behavior-changes-13#webview-color-theme)

**Comment by TheAlmightyBob** [comment]
Thanks @andrewbush-papa ! Sounds like a documentation update may be in order. Feel like submitting a PR? 😁

**Comment by mikekreeki** [comment]
Is there an alternative way to make dark mode detection work with the current version of react-native-webview and react-native 0.71?

**Comment by MonsieurBuffle** [comment]
I think it's not only a documentation problem about a deprecated feature (forceDarkOn).
According to [Android documentation](https://developer.android.com/about/versions/13/behavior-changes-13#webview-color-theme), at least on target SDK>=TIRAMISU (33), Webview should propagate the app's theme attribute.
I have an application (with expo) in production. My application settings are correctly set to use the device theme settings (`"userInterfaceStyle": "automatic"` in app.json).

If I set my device theme setting on dark, the application detect the change and put the dark theme for the status bar, and the android navigation bar (at the bottom), but the Webview is still light. ( `window.matchMedia('(prefers-color-scheme: light)').matches` is true)

So I think the system theme parameter is not correctly propagated to/by the Webview.

Any clue on this ? 😄 


**Environment:**
OS: Android
OS version: 13
expo : 48.0.0
react-native version: 0.71.6
react-native-webview version: 11.26.0

**Comment by isinha-onefc** [comment]
I'm facing this too. Please help!

**Comment by patlux** [comment]
I'm trying to fix this but it doesn't seem to work:

```kotlin
package expo.modules.userinterfacestylemodules

import android.os.Build
import android.content.Context
import android.webkit.WebView
import androidx.webkit.WebViewFeature
import androidx.webkit.WebSettingsCompat
import androidx.appcompat.app.AppCompatDelegate
import android.app.UiModeManager
import com.facebook.react.uimanager.UIManagerModule
import com.facebook.react.bridge.ReactApplicationContext
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import expo.modules.kotlin.exception.Exceptions
import expo.modules.kotlin.Promise
import kotlinx.coroutines.launch
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.CoroutineScope

class UserInterfaceStyleModule : Module() {
  private val moduleCoroutineScope = CoroutineScope(Dispatchers.Main)

  override fun definition() = ModuleDefinition {
    Name("UserInterfaceStyleModule")

    AsyncFunction("setAlgorithmicDarkeningAllowed") { viewTag: Int, enable: Boolean, promise: Promise ->

      if (WebViewFeature.isFeatureSupported(WebViewFeature.ALGORITHMIC_DARKENING)) {
        promise.reject("UNSUPPORTED", "setAlgorithmicDarkeningAllowed not supported", Exception("setAlgorithmicDarkeningAllowed not supported"))
        return@AsyncFunction
      }

      val rnContext = appContext.reactContext as? ReactApplicationContext ?: return@AsyncFunction
      val uiManager = rnContext.getNativeModule(UIManagerModule::class.java) as? UIManagerModule ?: return@AsyncFunction
      moduleCoroutineScope.launch {
        val webView = uiManager.resolveView(viewTag) as WebView
        val settings = webView.getSettings()
        WebSettingsCompat.setAlgorithmicDarkeningAllowed(settings, enable)
        promise.resolve(WebSettingsCompat.isAlgorithmicDarkeningAllowed(settings))
      }
    }
  }
}
```

I created a [native expo module](https://docs.expo.dev/modules/native-module-tutorial/) which calls `setAlgorithmicDarkeningAllowed` and sets it to `true` without any throwing exception, but the content is sill light and not dark of my webview.

Anyone an idea?

**Comment by patlux** [comment]
Ok I just fixed it

Add `<item name="android:isLightTheme">true</item>` to `res/values/styles.xml`:

```xml
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">@android:color/black</item>
    <item name="android:editTextStyle">@style/ResetEditText</item>
    <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="android:isLightTheme">true</item>
  </style>
  <style name="ResetEditText" parent="@android:style/Widget.EditText">
    <item name="android:padding">0dp</item>
    <item name="android:textColorHint">#c8c8c8</item>
    <item name="android:textColor">@android:color/black</item>
  </style>
  <style name="Theme.App.SplashScreen" parent="AppTheme">
    <item name="android:windowBackground">@drawable/splashscreen</item>
  </style>
</resources>
```

Create another `styles.xml` to `res/values-night/styles.xml` but with `<item name="android:isLightTheme">false</item>`: 

```xml
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">@android:color/black</item>
    <item name="android:editTextStyle">@style/ResetEditText</item>
    <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="android:isLightTheme">false</item>
  </style>
  <style name="ResetEditText" parent="@android:style/Widget.EditText">
    <item name="android:padding">0dp</item>
    <item name="android:textColorHint">#c8c8c8</item>
    <item name="android:textColor">@android:color/black</item>
  </style>
  <style name="Theme.App.SplashScreen" parent="AppTheme">
    <item name="android:windowBackground">@drawable/splashscreen</item>
  </style>
</resources>
```

Now call

```java
# for light mode
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)
# for dark mode
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)
```

If you use expo:

Create a file like plugin.js:

Hint: the below snippet is in typescript. remove all types to use it.

```ts
import {
  AndroidConfig,
  ConfigPlugin,
  withAndroidStyles,
  withDangerousMod,
} from '@expo/config-plugins'
import * as Styles from '@expo/config-plugins/build/android/Styles'
import fs from 'fs'
import fsAsync from 'fs/promises'

const withIsLightTheme: ConfigPlugin = (config) => {
  withDangerousMod(config, [
    'android',
    async (inlineConfig) => {
      const filePath = await Styles.getProjectStylesXMLPathAsync(process.cwd(), {
        kind: 'values-night',
      })
      const filePathParts = filePath.split('/')
      const _filePathName = filePathParts.pop()
      const filePathFolder = filePathParts.join('/')
      // values-night doesn't exist, so we need to create it
      if (!fs.existsSync(filePathFolder)) {
        fs.mkdirSync(filePathFolder)
      }

      fsAsync.writeFile(
        filePath,
        `
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:isLightTheme">false</item>
  </style>
</resources>
      `,
      )
      return inlineConfig
    },
  ])

  return withAndroidStyles(config, (inlineConfig) => {
    const setIsLightTheme = AndroidConfig.Styles.assignStylesValue(inlineConfig.modResults, {
      add: true,
      parent: AndroidConfig.Styles.getAppThemeLightNoActionBarGroup(),
      name: 'android:isLightTheme',
      value: 'true',
    })
    inlineConfig.modResults = setIsLightTheme
    return inlineConfig
  })
}

export default withIsLightTheme
```

Now add

```json
  "plugins": ["./plugin.js"]
```

to your `app.json`/`app.config.js`/`app.config.ts`

**Comment by jcarioti** [comment]
> Ok I just figured it out
> 
> Add `<item name="android:isLightTheme">true</item>` to `res/values/styles.xml`:
> 
> ```
> <resources xmlns:tools="http://schemas.android.com/tools">
>   <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>     <item name="android:textColor">@android:color/black</item>
>     <item name="android:editTextStyle">@style/ResetEditText</item>
>     <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
>     <item name="colorPrimary">@color/colorPrimary</item>
>     <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
>     <item name="android:isLightTheme">true</item>
>   </style>
>   <style name="ResetEditText" parent="@android:style/Widget.EditText">
>     <item name="android:padding">0dp</item>
>     <item name="android:textColorHint">#c8c8c8</item>
>     <item name="android:textColor">@android:color/black</item>
>   </style>
>   <style name="Theme.App.SplashScreen" parent="AppTheme">
>     <item name="android:windowBackground">@drawable/splashscreen</item>
>   </style>
> </resources>
> ```
> 
> Create another `styles.xml` to `res/values-night/styles.xml` but with `<item name="android:isLightTheme">false</item>`:
> 
> ```
> <resources xmlns:tools="http://schemas.android.com/tools">
>   <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>     <item name="android:textColor">@android:color/black</item>
>     <item name="android:editTextStyle">@style/ResetEditText</item>
>     <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
>     <item name="colorPrimary">@color/colorPrimary</item>
>     <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
>     <item name="android:isLightTheme">false</item>
>   </style>
>   <style name="ResetEditText" parent="@android:style/Widget.EditText">
>     <item name="android:padding">0dp</item>
>     <item name="android:textColorHint">#c8c8c8</item>
>     <item name="android:textColor">@android:color/black</item>
>   </style>
>   <style name="Theme.App.SplashScreen" parent="AppTheme">
>     <item name="android:windowBackground">@drawable/splashscreen</item>
>   </style>
> </resources>
> ```
> 
> Now call
> 
> ```java
> # for light mode
> AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)
> # for dark mode
> AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)
> ```


This fix is not working for me. We already had the `setDefaultNightMode` calls in our application previously, and the app theme seems to honor that change, but the web view is not honoring the app theme being changed to dark. I've added the two XML items for `isLightTheme`, but that doesn't seem to be doing anything either.

The web view (v12.0.3 in my case) is simply not honoring the app's dark theme change. RN v0.71.11.

**Comment by patlux** [comment]
> > Ok I just figured it out
> > Add `<item name="android:isLightTheme">true</item>` to `res/values/styles.xml`:
> > ```
> > <resources xmlns:tools="http://schemas.android.com/tools">
> >   <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
> >     <item name="android:textColor">@android:color/black</item>
> >     <item name="android:editTextStyle">@style/ResetEditText</item>
> >     <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
> >     <item name="colorPrimary">@color/colorPrimary</item>
> >     <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
> >     <item name="android:isLightTheme">true</item>
> >   </style>
> >   <style name="ResetEditText" parent="@android:style/Widget.EditText">
> >     <item name="android:padding">0dp</item>
> >     <item name="android:textColorHint">#c8c8c8</item>
> >     <item name="android:textColor">@android:color/black</item>
> >   </style>
> >   <style name="Theme.App.SplashScreen" parent="AppTheme">
> >     <item name="android:windowBackground">@drawable/splashscreen</item>
> >   </style>
> > </resources>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Create another `styles.xml` to `res/values-night/styles.xml` but with `<item name="android:isLightTheme">false</item>`:
> > ```
> > <resources xmlns:tools="http://schemas.android.com/tools">
> >   <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
> >     <item name="android:textColor">@android:color/black</item>
> >     <item name="android:editTextStyle">@style/ResetEditText</item>
> >     <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
> >     <item name="colorPrimary">@color/colorPrimary</item>
> >     <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
> >     <item name="android:isLightTheme">false</item>
> >   </style>
> >   <style name="ResetEditText" parent="@android:style/Widget.EditText">
> >     <item name="android:padding">0dp</item>
> >     <item name="android:textColorHint">#c8c8c8</item>
> >     <item name="android:textColor">@android:color/black</item>
> >   </style>
> >   <style name="Theme.App.SplashScreen" parent="AppTheme">
> >     <item name="android:windowBackground">@drawable/splashscreen</item>
> >   </style>
> > </resources>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now call
> > ```java
> > # for light mode
> > AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)
> > # for dark mode
> > AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)
> > ```
> 
> This fix is not working for me. We already had the `setDefaultNightMode` calls in our application previously, and the app theme seems to honor that change, but the web view is not honoring the app theme being changed to dark. I've added the two XML items for `isLightTheme`, but that doesn't seem to be doing anything either.
> 
> The web view (v12.0.3 in my case) is simply not honoring the app's dark theme change. RN v0.71.11.

This will only work for apps build with target sdk >= 33.

**Comment by jcarioti** [comment]
> @jcarioti This will only work for apps build with target sdk >= 33.

We are targeting SDK 33, still no luck:

```
        buildToolsVersion = "33.0.0"
        minSdkVersion = 28
        compileSdkVersion = 33
        targetSdkVersion = 33
 ```
 
 Any other ideas? I'm just going back through the "how to implement dark mode" docs and making sure nothing is out of the ordinary.

**Comment by jcarioti** [comment]
@patlux That was my mistake, your suggestions do work. We had a discrepancy where the AppCompatDelegate code was never getting called. I deleted my other replies so they're not adding any confusion.

**Comment by hitesh-c** [comment]
I still need help in this

**Comment by sddanila** [comment]
@patlux Thank you so much, the exp-version worked beautifully!

**Comment by prateekbh** [comment]
@patlux thank you, your solution worked perfectly.

**Comment by lipton-ice-tea** [comment]
Hi! I fixed this problem for myself - replaced `Theme.AppCompat.Light.NoActionBar` with `Theme.AppCompat.DayNight.NoActionBar` in file `res/values-night/styles.xml`

Full code
`
<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
    <item name="android:forceDarkAllowed">false</item>
    <item name="android:textColor">#000000</item>
</style>
`

**Comment by nasliedkov** [comment]
> Hi! I fixed this problem for myself - replaced `Theme.AppCompat.Light.NoActionBar` with `Theme.AppCompat.DayNight.NoActionBar` in file `res/values/styles.xml`
> 
> Full code
> 
> ```
> <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
>     <item name="android:forceDarkAllowed">false</item>
>     <item name="android:textColor">#000000</item>
> </style>
> ```

Thanks! U saved my day!

**Comment by JH7** [comment]
> Hi! I fixed this problem for myself - replaced `Theme.AppCompat.Light.NoActionBar` with `Theme.AppCompat.DayNight.NoActionBar` in file `res/values/styles.xml`
> 
> Full code
> 
> ```
> <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
>     <item name="android:forceDarkAllowed">false</item>
>     <item name="android:textColor">#000000</item>
> </style>
> ```

This worked for me, thank you!

To use this as an expo plugin:
```js
const { AndroidConfig, withAndroidStyles } = require("@expo/config-plugins");

const withIsLightTheme = (config) => {
  return withAndroidStyles(config, (inlineConfig) => {
    const styleParent = AndroidConfig.Styles.getStyleParent(
      inlineConfig.modResults,
      { name: "AppTheme" }
    );

    styleParent.$.parent = "Theme.AppCompat.DayNight.NoActionBar";

    const idx = inlineConfig.modResults.resources.style.findIndex(
      (s) => s.$.name === "AppTheme"
    );

    if (idx < 0) {
      throw new Error(
        'style name="AppTheme" in res/values/styles.xml not found'
      );
    }

    inlineConfig.modResults.resources.style[idx] = styleParent;

    return inlineConfig;
  });
};

module.exports = withIsLightTheme;

```
