### ISSUE TITLE
How to open http links in IOS?

### ISSUE THREAD

**Issue by ovsiannykov** [react-native-webview/react-native-webview#3607]
I'm creating the mobile web browser. But when i tried to open http links in my Webview i have got this message:

`{"canGoBack": false, "canGoForward": false, "code": -1022, "description": "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.", "didFailProvisionalNavigation": true, "domain": "NSURLErrorDomain", "loading": false, "target": 3373, "title": "", "url": ""}`

<img width="704" alt="Screenshot 2024-11-13 at 13 09 24" src="https://github.com/user-attachments/assets/40bfcdeb-5bea-4f54-a0d8-63fc127fae16">

**Comment by gguidotti** [comment]
Adding this to your Info.plist file(s) should fix the issue. Assuming that you want to visit http://example.com:

`
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>example.com</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
            <key>NSIncludesSubdomains</key>
            <true/>
        </dict>
    </dict>
</dict>
`

**Comment by ovsiannykov** [comment]
@gguidotti  Thanks! But i have tried this way before. Problem is in domain of my mobile app - it must be mobile web browser and it must be able to open any link. I can't create list with all http websites in the world. Also i have tried to resolve my problem by way of disabling **App Transport Security (ATS)**, but it didn't resolve my problem:

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

PS: i have checked it in real devices (IOS 17 and 18), and in booth modes (release ans debug)

**Comment by zhuzhuxingtianxia** [comment]
How to solve it?

**Comment by zhuzhuxingtianxia** [comment]
react-native-webview13.12.4 is the issue。upgrade to 13.12.5 or handle at a lower grade

**Comment by AwaisAliKolachi** [comment]
@ovsiannykov  were you ever able to fix this? I have a similar problem but the addresses are just IP addresses? I cant just add every ip address in allowed domains.

**Comment by orhangnc** [comment]
Adding the following App Transport Security (ATS) settings to Info.plist resolved the issue with loading any HTTP URL in WebView on iOS using [react-native-webview@13.16.0](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html):

```objective-c++
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
  <key>NSAllowsArbitraryLoadsInWebContent</key>
  <true/>
  <key>NSAllowsLocalNetworking</key>
  <true/>
</dict>
``` 
With these changes, WebView can access all HTTP and local network URLs without ATS-related connection errors.
Tested with: [react-native-webview@13.16.0](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)
