### ISSUE TITLE
kCFErrorDomainCFNetwork (error code 1) in real device but no in simulator

### ISSUE THREAD

**Issue by jimerino** [react-native-webview/react-native-webview#396]
When I try to obtain a local html file from device, I obtain an kCFErrorDomainCFNetwork (error code 1)

```
Domain: kCFErrorDomainCFNetwork
Error Code: 1
Description: The operation couldn't be completed (CDFErrorDomainCFNetwork error 1.)
```

That error only happens in real devices (in the emulator works fine).

This error disappears if:

i) I navigate to a http:// page (the error happen only when I read a html file from local)
ii) If I use useWebKit={false}

This is my WebView:

```jsx
<WebView
  originWhitelist={['*']}
  source={{ uri: "file://xx/xxx/xxx.html" }}
  allowFileAccess={true}
  useWebKit={true}
/>
```

Regards,
Jose I. Merino

**Comment by jamonholmgren** [comment]
Thanks for reporting, @jimerino ! If you get a chance to submit a PR to fix this issue, we would be happy to test it.

**Comment by Arjan-Zuidema** [comment]
The issue is also present on Android, but with a different error: `net::ERR_ACCESS_DENIED`

Works on a simulator, but not on a real device

**Comment by jimerino** [comment]
@Arjan-Zuidema I've have this problem in Android and solved with:

i) Make sure the props in WebView originWithilist and allowFileAccess are proper

        originWhitelist={['*']}
        allowFileAccess={true}

ii) If the local file is in a directory outside from the assigned app directories, you must give read access to external storage:

https://developer.android.com/reference/android/Manifest.permission.html#READ_EXTERNAL_STORAGE

If is in the emulator, I think the key factor is the ii) because the emulator has less restrictions than a real device.

In iPhone I suspect that in UIWebView the method to read from http server and local file are the same: load(:_), but in WKWebView load(:_) is only for http server and must use loadHTMLString(_:baseURL:) method to local files.

After work I'll try to watch the code and see if that suspect is a founded suspicion or not...

**Comment by Arjan-Zuidema** [comment]
@jimerino I don't have this issue in version 4.1.0 but in any versions above I get `net::ERR_ACCESS_DENIED`

I already have set the props

```
originWhitelist={['*']}
allowFileAccess={true}
```

My source props are
```
source: {
 uri: "file:///data/user/0/<appid>/files/embed/index.html"
}
```

`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />` is set in `AndroidManifest.xml`
I also tried asking for permissions on the fly, but that does not seem to fix the problem.

**Comment by jimerino** [comment]
@Arjan-Zuidema 

/data/user/<userId>/... Not completly sure but and userId = 0 gives me a clue that you're trying access to user root folder

Have you try to read an html file from cache folder?

**Comment by Arjan-Zuidema** [comment]
@jimerino /data/user/0/ is what RNFS.CachesDirectoryPath gives me, I just solved it by using RNFS.ExternalCachesDirectoryPath. Thanks for your input!

**Comment by jimerino** [comment]
@jamonholmgren 

I've made a PR. Be gentle, it's my first PR :)

This post gives me the clue:

https://stackoverflow.com/questions/35847493/loading-local-file-works-fine-in-simulator-but-crash-on-device

The only thing I do is check if there's a host in the URL and call to loadRequest if true and the new method loadFileURL if not (but, please, check it. Don't know if there's a collateral damage in that simple if).

Regards,
Jose I. Merino

**Comment by EstebanBP** [comment]
Your PR didn't work for my case but I think it's related too (#471)
And also this http://www.openradar.me/45346962

**Comment by Lemo-yxk** [comment]
in visitSource method change :

`[_webView loadFileURL:request.URL allowingReadAccessToURL:request.URL];`
 
to

```
NSString*documentPath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,NSUserDomainMask,YES).firstObject;
        [_webView loadFileURL:request.URL allowingReadAccessToURL:[NSURL fileURLWithPath:documentPath]];
```

in didMoveToWindow method add:

`[_webView.configuration.preferences setValue:@YES forKey:@"allowFileAccessFromFileURLs"];`

it works for me.

**Comment by essejose** [comment]
> in visitSource method change :
> 
> `[_webView loadFileURL:request.URL allowingReadAccessToURL:request.URL];`
> 
> to
> 
> ```
> NSString*documentPath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,NSUserDomainMask,YES).firstObject;
>         [_webView loadFileURL:request.URL allowingReadAccessToURL:[NSURL fileURLWithPath:documentPath]];
> ```
> 
> in didMoveToWindow method add:
> 
> `[_webView.configuration.preferences setValue:@YES forKey:@"allowFileAccessFromFileURLs"];`
> 
> it works for me.

works for me

**Comment by smxdevst** [comment]
@Lemo-yxk Thank you it works for me as well

**Comment by gytisgreitai** [comment]
@Lemo-yxk thanks, saved me also! Can you explain why this is needed and what does it do?

**Comment by wisungyo** [comment]
> in visitSource method change :
> 
> [_webView loadFileURL:request.URL allowingReadAccessToURL:request.URL];
> 
> to
> 
> NSString*documentPath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,NSUserDomainMask,YES).firstObject;
>         [_webView loadFileURL:request.URL allowingReadAccessToURL:[NSURL fileURLWithPath:documentPath]];
> in didMoveToWindow method add:
> 
> [_webView.configuration.preferences setValue:@YES forKey:@"allowFileAccessFromFileURLs"];
> 
> it works for me.

It works in RN 0.73. You save my life. Thanks!

**Comment by jamonholmgren** [comment]
Irony, I hit this error (not in WebView, unfortunately, in a websocket connection) and first result in Google is this issue. 😆
